import os
import json
import requests
from fastapi import APIRouter, HTTPException, Request
from pydantic import BaseModel
from dependencies import limiter

try:
    from google import genai
    from google.genai import types
except ImportError:
    genai = None

router = APIRouter()

class OptimizeRequest(BaseModel):
    analysis_data: dict

def _get_mock_code() -> str:
    return """<!-- Optimized SEO Headers Generated by Antilabs AI -->
<title>Ultimate Guide to Your Industry | Outrank Competitors</title>
<meta name="description" content="Discover the best strategies and tools. We analyzed top trends to bring you unparalleled insights into your market." />
<meta name="keywords" content="AI analytics, predictive modeling, real-time metrics" />
<meta property="og:title" content="Ultimate Guide to Your Industry | Outrank Competitors" />
<meta property="og:description" content="Discover the best strategies and tools. We analyzed top trends to bring you unparalleled insights." />
<meta property="og:type" content="website" />
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:title" content="Ultimate Guide to Your Industry" />
<meta name="twitter:description" content="Discover the best strategies and tools." />
"""

@router.post("/optimize")
@limiter.limit("5/minute")
async def optimize(request: Request, body: OptimizeRequest):
    try:
        system_prompt = """
        You are an elite SEO Expert. Based on the provided competitor analysis data (JSON), 
        generate the EXACT HTML <head> code snippet (Meta Title, Description, Keywords, Open Graph, Twitter Cards, etc.) 
        that will optimize the user's website ('Our Website') to beat the competitor.
        
        Focus heavily on incorporating the 'trending_keywords' into the title and description, 
        and address any 'our_weaknesses' (e.g. missing meta tags).
        
        Return ONLY the raw HTML code snippet. Do NOT wrap it in markdown like ```html. 
        Do not include any explanations. Just the raw HTML tags.
        """
        
        user_prompt = f"=== ANALYSIS DATA ===\n{json.dumps(body.analysis_data, indent=2)}"
        
        # 1. Check OpenAI
        openai_api_key = os.environ.get("OPENAI_API_KEY", "")
        if openai_api_key and openai_api_key != "your_openai_api_key_here":
            model = os.environ.get("OPENAI_MODEL", "gpt-4o-mini")
            print(f"[optimize] Using OpenAI ({model}) for SEO optimization...")
            headers = {"Authorization": f"Bearer {openai_api_key}", "Content-Type": "application/json"}
            payload = {
                "model": model,
                "messages": [
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt}
                ],
                "temperature": 0.5,
            }
            response = requests.post("https://api.openai.com/v1/chat/completions", headers=headers, json=payload, timeout=60)
            response.raise_for_status()
            code = response.json()["choices"][0]["message"]["content"].strip()
            return {"code": code.replace("```html", "").replace("```", "").strip()}

        # 2. Check Groq
        groq_api_key = os.environ.get("GROQ_API_KEY", "")
        if groq_api_key and groq_api_key != "your_groq_api_key_here":
            model = os.environ.get("GROQ_MODEL", "llama-3.3-70b-versatile")
            print(f"[optimize] Using Groq ({model}) for SEO optimization...")
            headers = {"Authorization": f"Bearer {groq_api_key}", "Content-Type": "application/json"}
            payload = {
                "model": model,
                "messages": [
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt}
                ],
                "temperature": 0.5,
            }
            response = requests.post("https://api.groq.com/openai/v1/chat/completions", headers=headers, json=payload, timeout=60)
            response.raise_for_status()
            code = response.json()["choices"][0]["message"]["content"].strip()
            return {"code": code.replace("```html", "").replace("```", "").strip()}

        # 3. Check Gemini
        gemini_api_key = os.environ.get("GEMINI_API_KEY", "")
        if gemini_api_key and gemini_api_key != "your_gemini_api_key_here":
            if not genai:
                raise ImportError("google-genai SDK missing")
            print("[optimize] Using Gemini (gemini-2.5-flash) for SEO optimization...")
            client = genai.Client(api_key=gemini_api_key)
            prompt = system_prompt + "\n\n" + user_prompt
            response = client.models.generate_content(
                model="gemini-2.5-flash",
                contents=prompt,
                config=types.GenerateContentConfig(temperature=0.5),
            )
            code = response.text.strip()
            return {"code": code.replace("```html", "").replace("```", "").strip()}

        # 4. Fallback mock
        return {"code": _get_mock_code()}

    except Exception as e:
        print(f"[optimize] Error: {e}")
        return {"error": str(e), "code": _get_mock_code()}
